### ISSUE TITLE
request for releasing hydro-deb

### ISSUE THREAD

**Issue by k-okada** [ros-visualization/view_controller_msgs#2]
We're big fun of view_controller_msgs , but could not find deb for hydro.

**Comment by aleeper** [comment]
I guess I'm the maintainer for this. Let me get back up to speed on the release process and I will try to release within the next few days.

**Comment by k-okada** [comment]
ping

**Comment by aleeper** [comment]
Hi Kei,

What is your use case for these messages? I recently released a new view controller, https://github.com/ros-visualization/rviz_fixed_view_controller, which to me renders these messages and the rviz_animated_view_controller obsolete, since you can just publish a TF frame for the camera to follow.

Or, perhaps you specifically need the message types for another use?

**Comment by k-okada** [comment]
we control rviz view from ps3/xbox joystick, @garaemon will explain more detail

**Comment by garaemon** [comment]
We are controlling rviz from joystick devices.( https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_teleop_joy/src/jsk_teleop_joy/plugin/joy_rviz_view_controller.py )

Our code uses CameraPlacement message.

Do you recommend to use rviz_fixed_view_controller and publish `/tf` from the joystick program in our case?

**Comment by aleeper** [comment]
Ok, I looked through your code and it made me realize that there is value to having a view controller with the "orbit" interface the way I have in rviz_animated_view_controller.

While rviz_fixed_view_controller is very generic, it has the disadvantage that it forces you to write your own "control" code to figure out how to move the TF frame in a way that replicates an orbit controller. (I suppose an alternative approach would be to provide a library that helps do "orbit" manipulation of a TF frame).

I'll release this; hopefully it "just works".
You are using `rviz_animated_view_controller` also, correct?

**Comment by garaemon** [comment]
> You are using rviz_animated_view_controller also, correct?

Exactly.

> I'll release this; hopefully it "just works".

Thank you.

**Comment by aleeper** [comment]
Released into hydro and indigo. Please wait a couple days and hopefully it will show up in ros-shadow-fixed.

I'll release rviz_animated_view_controller next, but I can't do it until the pull requests against ros/ros-distro go through for this package.

**Comment by aleeper** [comment]
Just to finish this thread, hydro debs for this and for `rviz_animated_view_controller` are now in ros-shadow-fixed in hydro.

To test it out, you can do `roslaunch rviz_animated_view_controller demo.launch`.
