### ISSUE TITLE
Jade release, please?

### ISSUE THREAD

**Issue by wkentaro** [ros-visualization/view_controller_msgs#3]

**Comment by k-okada** [comment]
I think we already have jade, kinetic, (https://github.com/ros-gbp/view_controller_msgs-release), but we still need release for lunar and melodic.

if no one can release this to newer rosdistro (lunar/melodic), can someone @wjwwood ? @dirk-thomas ? give me write access to this repository and , so https://github.com/ros-gbp/view_controller_msgs-release that I can release as a ROS Orphaned Package Maintainer initiatives ?

**Comment by dirk-thomas** [comment]
@aleeper Friendly ping.

**Comment by dirk-thomas** [comment]
> can someone give me write access to this repository and ros-gbp/view_controller_msgs-release ...

Done.

**Comment by k-okada** [comment]
@dirk-thomas 
thanks, I have released to lunar and melodic (https://github.com/ros/rosdistro/pull/19047, 
https://github.com/ros/rosdistro/pull/19048)

Can you also give me the permission to release 
ivcon/ivcon-release (https://github.com/ros/ivcon/issues/4#issuecomment-411313160)
and  https://github.com/ros/convex_decomposition / https://github.com/ros-gbp/convex_decomposition-release ? (see https://github.com/ros/convex_decomposition/issues/7 )

thanks in advance.
